os: Visual Studio 2017
configuration: Release
install:
  - choco install gitversion.portable 
  - choco install opencover.portable
  - pip install codecov
before_build:
  - nuget restore
  - gitversion /output buildserver
build:
  project: Edtf.sln
after_test:
  - OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:".\EdtfTests\bin\%CONFIGURATION%\EdtfTests.dll" -filter:"+[Edtf]*" -hideskipped:All -output:.\EdtfTests\bin\%CONFIGURATION%\coverage.xml
  - codecov -X gcov -f ".\EdtfTests\bin\%CONFIGURATION%\coverage.xml"
cache:
  - packages -> **\packages.config
skip_commits:
  files:
    - .gitattributes
    - .gitignore
